version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

languages:
  en:
    path: /en/
    build:
      mkdocs:
        configuration: mkdocs.yml
  ja:
    path: /ja/
    build:
      mkdocs:
        configuration: mkdocs.ja.yml