name: "Test MkDocs Build"

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build-docs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]
      - run: mkdocs build --strict
