name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev,test]
    - name: Pytest
      run: |
        pytest --cov=src/easybench tests/

  test-summary:
    name: Wait for all test jobs
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
      - name: Check job results
        run: |
          if grep -q '"conclusion":"failure"' <<< "${{ toJson(needs) }}"; then
            echo "At least one matrix job failed"
            exit 1
          else
            echo "All matrix jobs succeeded"
          fi
